### ISSUE TITLE
Loss function

### ISSUE THREAD

**Issue by Ehteshamciitwah** [chunbolang/DCP#2]
Hello, Thank you for sharing your work. I was reading your code and found that you are using only one AUX loss, while in the paper both aux losses are mentioned.  Please elaborate

**Comment by chunbolang** [comment]
Hi, thanks for your interest!

We adopt the average loss of support and query branches, please check [here](https://github.com/chunbolang/DCP/blob/main/model/DCP.py#L441-L444).
